# Generated by Django 4.1.3 on 2022-11-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('modeli', models.CharField(max_length=30)),
                ('narxi', models.IntegerField(default=30)),
            ],
        ),
    ]
